server:
  port: 9000
  context-path: /activitystream 

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
      
  datasource:
    url: jdbc:mysql://localhost:3306/activitystreamdb?useSSL=false
    username: root
    password: password
    